host: catarse.me
base_url: "http://catarse.me"
blog_url: "http://blog.catarse.me"
email_contact: contato@catarse.me
email_payments: financeiro@catarse.me
email_projects: projetos@catarse.me
email_system: system@catarse.me
email_no_reply: no-reply@catarse.me

facebook_url: "http://facebook.com/catarse.me"
facebook_app_id: 173747042661491

twitter_username: "Catarse_"

mailchimp_url: "http://catarse.us5.list-manage.com/subscribe/post?u=ebfcd0d16dbb0001a0bea3639&amp;id=149c39709e"

