import { ProjectIntegration } from "./project-integration";
import { TimeDescription } from "./time-description";

export type Project = {
    project_id: number;
    category_id: number;
    project_name: string;
    headline: string;
    permalink: string;
    mode: string;
    state: "deleted" | "rejected" | "draft" | "in_analysis" | "approved" | "online" | "waiting_funds" | "failed" | "successful";
    state_order: "archived" | "created" | "created" | "sent" | "publishable" | "published" | "published" | "finished" | "finished";
    online_date: string;
    recommended: boolean;
    project_img: string;
    remaining_time:	TimeDescription;
    expires_at:	string;
    pledged: number;
    progress: number;
    state_acronym: string;
    owner_name: string;
    city_name: string;
    full_text_index: string | null;
    open_for_contributions:	boolean;
    elapsed_time: TimeDescription;
    score: number;
    contributed_by_friends: boolean;
    project_user_id: number;
    video_embed_url: string;
    updated_at:	string;
    owner_public_name: string;
    zone_expires_at: string;
    common_id: string;
    is_adult_content: boolean;
    content_rating:	number;
    integrations: ProjectIntegration[];
    category_name: string;
    active_saved_projects: boolean;
    in_reminder: boolean;
};
